butaneprotocol/blaze-cardano

.changeset/serious-ladybugs-drum.md
packages/blaze-emulator/src/emulator.ts
packages/blaze-sdk/src/blaze.ts
packages/blaze-tx/src/tx.ts
packages/blaze-tx/src/value.ts

Values enforce no 0-quantity assets, redeemers have correct indexes, transaction network id is attached, various emulator patches.

Patches: Redeemer ordering + Value invariant

---

.changeset/fuzzy-parents-heal.md
packages/blaze-wallet/src/hotsingle.ts

I want to be able to pass both the payment and staking part as private keys in order to make this wallet. It shouldn't have to just be an enterprise address.

Add option to pass staking part to HotSingleWallet

---

.changeset/orange-socks-kiss.md
examples/blockfrost/index.js
packages/blaze-query/src/blockfrost.ts

Fix type mismatch between Blockfrost API and `BlockfrostUTxO` on amount quantity. API actually returns `string` and it should be cast to `bigint`.

bugfix: Fix BlockfrostUTxO type error

---

packages/blaze-tx/src/tx.ts

When completing the transaction we are missing the auxilary data.
This results in an error when submitting the tx `MissingTxMetadata`

fix: add auxilary data to completed tx

---

.vscode/settings.json
packages/blaze-query/src/kupmios.ts
packages/blaze-query/src/types.ts

Added `purposeTag` to ensure consistency between purpose strings and tag numbers as the `RedeemerPurpose` enum's indexes are still inconsistent with the `RedeemerTag` values in @cardano-sdk/core v0.35.0.
``` js
export declare enum RedeemerTag {
Spend = 0,
Mint = 1,
Cert = 2,
Reward = 3,
Voting = 4,
Proposing = 5
}
```
``` js
export declare enum RedeemerPurpose {
spend = "spend",
mint = "mint",
certificate = "certificate",
withdrawal = "withdrawal",
propose = "propose",
vote = "vote"
}
```

Add `purposeToTag` to align `RedeemerPurpose` enum with `RedeemerTag` values

---

.changeset/stupid-buttons-arrive.md
packages/blaze-query/src/kupmios.ts

Attempt at fixing `resolveScript` on Kupmios as reported by:
https://discord.com/channels/946071061567529010/1019685247870308362/1266074710756692051
I used the recently added `getScriptRef` to the Blockfrost provider as a reference and tried to make the following result be the same for both providers:
```typescript
// preview testnet
const provider = new Kupmios(kupoUrl, ogmiosUrl);
const txIns = [
new TransactionInput(
"74baf638a18a6ab54798cac310112af61cb1f1d6eacb8c893a10b6877cf71a8d",
1,
),
new TransactionInput(
"036ed48c89169a9c4e475e08a6d22ea1e09ba8a6a6cfbabfa4f1deefd269652c",
0,
),
];
const resolvedOutputs = await provider.resolveUnspentOutputs(txIns);
for (const result of resolvedOutputs) {
if (result.output().scriptRef()) console.log(result.output().scriptRef().hash());
}
```

fix: Fix resolveScript on Kupmios

---

packages/blaze-query/src/blockfrost.ts
packages/blaze-tx/src/tx.ts

This fixes two issues:
- Blockfrost submission was including an incorrect header, preventing finality.
- Script data hash generation was using outdated models for Conway.

chore: fix blockfrost API request

---

.changeset/afraid-ads-happen.md
packages/blaze-tx/src/tx.ts

This helps blaze cross the era boundary gracefully, in theory.
Credit to @cjkoepke
Supersedes https://github.com/butaneprotocol/blaze-cardano/pull/129

chore: make script data hash only valid for chang

---

.changeset/serious-wasps-fix.md
.github/workflows/check.yml
.github/workflows/release.yml
package.json
packages/blaze-blueprint/package.json
packages/blaze-blueprint/tsconfig.json
packages/blaze-core/package.json
packages/blaze-core/tsconfig.json
packages/blaze-emulator/package.json
packages/blaze-emulator/tsconfig.json
packages/blaze-ogmios/package.json
packages/blaze-ogmios/tsconfig.json
packages/blaze-query/package.json
packages/blaze-query/tsconfig.json
packages/blaze-sdk/package.json
packages/blaze-sdk/tsconfig.json
packages/blaze-tsconfig/base.json
packages/blaze-tx/package.json
packages/blaze-tx/tsconfig.json
packages/blaze-uplc/package.json
packages/blaze-uplc/tsconfig.json
packages/blaze-vm/package.json
packages/blaze-vm/tsconfig.json
packages/blaze-wallet/package.json
packages/blaze-wallet/tsconfig.json
pnpm-workspace.yaml
turbo.json

When using `"type": "module"` in a project using blaze, some dependencies imports are mixed since the default type is CommonJS, which leads to errors like `Error: require() of ES Module ...`.  
Also using `NODE_ENV=production` ensures any dependencies down the line prefer to use their optimized builds (the dependency graph is too big to analyze heh, but this is the defacto)

build: update package.json to be consistent

---

packages/blaze-query/package.json
packages/blaze-query/src/u5c.ts
pnpm-lock.yaml

In this PR we update the u5c provider to use the latest upstream packages. These new versions include the following changes:
- Conway-specific structs (new costmodel, new certs, etc)
- The packages now provide both esm and commonjs builds

chore(query): update u5c provider to upstream sdk v0.5.0

---

packages/blaze-tx/src/tx.ts

This PR introduces the ability to specify UTxOs to be used as collateral, if applicable.
This is helpful because some wallets allow the end-user to specify a "collateral UTxO(s)". If that is the case, a dApp should do their best to avoid spending that UTxO, as it could cause issues for the user on other dApps. Currently, blaze does not support such behavior; collateral comes from the full set of UTxOs provided to it, any of which may be spent in the transaction.

Support Providing Specific Collateral

---

.changeset/late-geese-tie.md
packages/blaze-tx/src/tx.ts

The recent collateral changes introduced caused issues when balancing collateral change if a collateral utxo was provided. This change fixes that issue

Fix balanceCollateralChange

---

packages/blaze-tx/src/tx.ts

Add the ability to set a differente collateral return address than the collateral change. Seems useful for complex/specific scenarios

feat: add collateral change address

---

.changeset/flat-plants-roll.md
packages/blaze-tx/src/tx.ts

When evaluating there is a diff between the outputChange and the fee set in the tx. This is due to substracting the preliminaryFee both the first time we calculate the excessValue and when merging in the modifiied line

fix: consider preliminaryFee on fee calculation

---

.changeset/olive-comics-teach.md
packages/blaze-sdk/src/blaze.ts

This PR submit transactions through the wallet by default, while retaining the ability to shortcut to the provider.

chore: submit transactions through the wallet by default

---

.changeset/mighty-news-try.md
packages/blaze-tx/src/tx.ts

Fix a small fee calculation issue. Final Size should be initialized to draft_size as after draft_tx is initialize the witness set is updated so the actual size changes but its not accounted in the fee calculation. This could lead to some edge cases where the tx is balanced, size remains the same and the tx_size doesn't change so the fee will be lower than it should

fix: wrong final_size calculation

---

packages/blaze-core/src/params.ts
packages/blaze-emulator/src/emulator.ts
packages/blaze-query/src/blockfrost.ts
packages/blaze-query/src/maestro.ts
packages/blaze-tx/src/tx.ts
packages/blaze-uplc/src/utils.ts

This pull request corrects the collateral percentage calculation. 
The collateral percentage was previously defined as a rational number (e.g. 150/100), but it should be defined as a natural number (e.g. 150) to be consistent with the genesis configs.  
This change ensures consistency in the collateral percentage, correct calculation, and avoids the issue of collateral being 100 times larger than expected in Kupmios povider.
Additionally, this pull request adds initial support for PlutusV3 scripts in the blaze-uplc package. 
This initial support may require additional commits to fully implement the feature.

Fix correct collateral percentage calculation and add initial support for PlutusV3 script

---

.changeset/gentle-tools-own.md
packages/blaze-query/src/maestro.ts

Race condition checking the utxos array length while a fetch may still be happening asynchronously highlighed below.
```typescript
const utxos: TransactionUnspentOutput[] = [];
for (const maestroUTxO of response.data) {
//...snip
fetch(`${this.url}${query2}?with_cbor=true`, {
headers: this.headers(),
})
.then((resp) => resp.json())
.then((json) => {
//...snip
utxos.push(new TransactionUnspentOutput(txIn, txOut));
//...snip
});
}
// This check can happen before the async fetch in the for loop above completes
if (utxos.length !== 1)  {
throw new Error(
"getUnspentOutputByNFT: Expected 1 UTxO, got " + utxos.length,
);
}
```
I moved the array length check to before the fetch using the initial `response.data` array instead which should have the same behavior.   I then removed the for loop …

Adjust Maestro::getUnspentOutputByNFT flow to prevent race condition.

---

.changeset/eleven-walls-return.md
packages/blaze-core/src/util.ts
packages/blaze-emulator/src/provider.ts
packages/blaze-emulator/test/Emulator.test.ts
packages/blaze-emulator/test/util/index.ts
packages/blaze-ogmios/src/unwrapped.ts
packages/blaze-query/src/blockfrost.ts
packages/blaze-query/src/index.ts
packages/blaze-query/src/kupmios.ts
packages/blaze-query/src/maestro.ts
packages/blaze-query/src/provider.ts
packages/blaze-tx/src/tx.ts
sites/docs/next-env.d.ts

- Method to lock a UTXO at a burn address with minimum ADA and a provided script as a script ref
- Provider query to resolve a script to it's deployment utxo (for using as a reference input)
This can also open up the discussion as to how this feature should function and should be extended moving forward.
Note that this is part of one of the F12 Catalyst proposals for Blaze https://www.lidonation.com/en/proposals/blaze-tools-for-handling-and-managing-script-deployments-f12

Basic Script Deployment Utils

---

.changeset/green-bags-greet.md
.changeset/young-days-bow.md
packages/blaze-core/src/util.ts
packages/blaze-tx/src/tx.ts
packages/blaze-tx/test/tx.test.ts

Since `preview` has fully migrated to protocol version 10, we can fully migrate to encoding the redeemer set as a map, rather than an array. Changes include:
- Exporting `setIsConway` utility function from `@blaze-cardano/core`.
- Setting Conway era globally in the `TxBuilder` constructor.
- Reformatting the `getScriptDataHash` to `getScriptData` so we have complete data for later debugging scenarios.
- Added a utility method to get the script data hash for backward compatability.

Fix: Use a Redeemer Map When Generating a Script Data Hash

---

.changeset/seven-teachers-wave.md
packages/blaze-tx/src/tx.ts

Fixes a bug where encoded datums in the scriptData were being added even if the datum was empty. This fix is required for the upcoming hard fork event.

fix: datums in script data

---

.changeset/polite-carrots-smash.md
packages/blaze-tx/src/tx.ts

In a Hydra head, (and other contexts, but hydra is the most realistic) transactions can have a fee of `0`. A transaction with a fee of zero will cause issues with the current transaction balancing. This PR gracefully handles zero fee transactions.

Support Zero Fee Transactions

---

.changeset/shaggy-turkeys-end.md
packages/blaze-query/src/blockfrost.ts

There were new cost models added to PlutusV3 that do not follow the ordering convention of alphabetical key ordering. Therefore, the sort moves values to places where they are not in the latest protocol parameter update transaction. Fortunately, blockfrost returns a `cost_models_raw` which is already in the ordering that exists on the ledger.

Fix PlutusV3 cost model encoding in Blockfrost

---

.changeset/poor-sheep-fetch.md
packages/blaze-tx/src/tx.ts

If a user forgets to add a redeemer to an input, the `buildTransactionWitnessSet` method will just assume it's suppose to be a native script. This adds better error handling by:
- Including the script hash in the error message.
- Reminding the user to check if they missed a redeemer.

Error Handling Fix

---

.changeset/metal-vans-begin.md
packages/blaze-tx/src/tx.ts
packages/blaze-tx/tests/tx/tx.test.ts

This PR allows users to opt out of coin selection when completing a transaction. This is useful for cases where knowledge of selected inputs is important for building datums, and mirror's Lucid's behavior.

Allow Coin Selection Opt-Out

---

.github/workflows/docs.yml

The deploy pipeline is broken for building docs due to [this issue](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/), where `actions/upload-pages-artifact@v2` has been deprecated and requires v3 in order to run.

fix: outdated actions

---

.changeset/rude-islands-bathe.md
packages/blaze-emulator/src/emulator.ts

This adds a helper for testing valid multisigned transactions, since htat was pretty awkward.
Usable like this:
```ts
const tx = await emulator.as(Funder, async (blaze) => {
return fund(
configs,
blaze,
fourthScriptInput,
vendor,
[
{
date: new Date(Number(slot_to_unix(Slot(10)))),
amount: makeValue(25_000_000n),
},
{
date: new Date(Number(slot_to_unix(Slot(12)))),
amount: makeValue(25_000_000n, ["b".repeat(56), 50n]),
},
],
[
Ed25519KeyHashHex(await fund_key(emulator)),
Ed25519KeyHashHex(await vendor_key(emulator)),
],
);
});
await emulator.expectValidMultisignedTransaction([Funder, Vendor], tx);
```

Emulator "multisignature" helper

---

.changeset/slimy-points-bathe.md
packages/blaze-data/src/index.ts
packages/blaze-data/test/index.test.ts

There was a bug where having an optional reference type wouldn't be parsed correctly, as when resolving the type the optional property would be ignored.

Fix (data): Optional type references parsed correctly

---

.changeset/eight-berries-tell.md
packages/blaze-uplc/wasm/build.sh

Updates the wasm pack script to remove default .gitignore file from packages. This was preventing them from being included in published files.

Include UPLC WASM Files in Published Package
