butaneprotocol/blaze-cardano

.changeset/rude-chicken-float.md, packages/blaze-emulator/package.json, packages/blaze-emulator/src/emulator.ts, packages/blaze-emulator/src/provider.ts, packages/blaze-emulator/test/Emulator.test.ts, packages/blaze-emulator/test/EmulatorProvider.test.ts, packages/blaze-emulator/test/util/index.ts, packages/blaze-sdk/package.json, packages/blaze-sdk/src/index.ts, packages/blaze-tx/src/tx.ts, packages/blaze-tx/src/value.ts, pnpm-lock.yaml
- Adds tests for spending, minting, and withdrawing from scripts
- Fixes to transaction building and validation logic
=> Emulator Tests and Transaction Logic Patches

examples/blockfrost/index.js, packages/blaze-core/src/util.ts, packages/blaze-query/src/blockfrost.ts, packages/blaze-tx/src/tx.ts, packages/blaze-tx/src/value.ts
Implement `getUnspentOutputs` for Blockfrost provider.
Tested with:
```
BLOCKFROST_PROJECT_ID="preview..." bun run examples/blockfrost/index.js
```
~~TODO: pagination~~ ✅
=> Blockfrost getUnspentOutputs

.changeset/real-wasps-compete.md, packages/blaze-tx/package.json, packages/blaze-tx/src/data.ts, packages/blaze-tx/test/data.test.ts, pnpm-lock.yaml
Type checking for Plutus data serde using Lucid's patterns, + schema builders using TypeBox
=> Data serialisation type checking and schema building

.changeset/nervous-hats-bathe.md, .prettierignore, packages/blaze-blueprint/package.json, packages/blaze-blueprint/src/cli.ts, pnpm-lock.yaml
mostly just gives us a nice help menu
=> add commander to blueprint cli

packages/blaze-query/src/blockfrost.ts, packages/blaze-tx/src/tx.ts
Adds the ability to supply a datum to an output with a payment address.
=> Add Support for Optional Datums with Payment Addresses

.changeset/nine-taxis-knock.md, packages/blaze-tx/src/tx.ts
Normally this shouldn't be used, but having this pressure release valve is more useful than just minimum fee while we try to fix the bug in fee estimation. I took efforts to make sure people let us know if they need this, so we can address any bugs
=> Add a feePadding option

.changeset/nasty-emus-teach.md, packages/blaze-tx/src/tx.ts
Having an option to print the partial transaction up to certain point is useful for debugging purposes
=> feat: add toCbor() 

README.md
**Summary:**
- This adds distinction to providers and also to show available external providers
=> chore: added distinction between providers in readme

.changeset/weak-squids-camp.md, packages/blaze-emulator/src/emulator.ts, packages/blaze-tx/src/tx.ts
Description here: https://github.com/butaneprotocol/blaze-cardano/pull/172#discussion_r1773656982
=> Fixes Collateral Calculation

packages/blaze-emulator/src/emulator.ts
gotta go fast brrr (and not fuck up the timeline in the process)
=> express block duration in slots, not ms

.changeset/fifty-cheetahs-grin.md, packages/blaze-tx/src/tx.ts
This tries to avoid issues when creating the collateral return output.
Seeing an issue where its below min utxo. This I guess should reduce the possibilities of it happening a lot?
```
84a900828258203728d6e64fbd756db0edefe78ffa59af0a8afe0a00c21f0d1db4c38c552619cc018258203bb7020f14e842b0275ded6fa40a7f116c15f69015d4bc7657b334ea04dc47cc0101858258393184cc25ea4c29951d40b443b95bbc5676bc425470f96376d1984af9ab2c967f4bd28944b06462e13c5e3f5d5fa6e03f8567569438cd833e6d1a000f424082583901c32ccfed97a377491819d236be8fb2372f6313519de0167806ffb417140ca32b40d8757a8a91fe1136ac6495f4c74f44e77ba517e6e298bb1a000f424082583901dabe9ea6444e5b00264f4b8d804efb7a7125d1976fff2323bcc12fa8267aa9c2245329ff79213c9fbda46682636ace318ce7c4573c308900821a00129c92a1581c8af7c892a26bb5d3b4c411c68fc92dda982ab7b8d228bb06a31fdb2aa1570 …
```
=> fix: collateral output min utxo not taken into account

.changeset/friendly-rocks-destroy.md, .changeset/red-planes-sell.md, packages/blaze-tx/src/tx.ts
This is a change that stops the utxo set growth that we see in a hydra head when using blaze
=> Don't create zero value change output

.changeset/smooth-adults-argue.md, packages/blaze-emulator/src/emulator.ts, packages/blaze-tx/src/tx.ts, packages/blaze-uplc/src/decoder.ts
Adds the ability to donate some Lovelace back to the treasury.
=> Add donation support

.changeset/calm-boats-fetch.md, packages/blaze-core/src/types.ts, packages/blaze-tx/src/tx.ts, packages/blaze-tx/tests/tx/tx.test.ts
Also fixes an error message to reduce noise, though soon we'll make this a custom error
=> Add deregistration; fix delegation

packages/blaze-blueprint/package.json, packages/blaze-blueprint/src/blueprint.ts, packages/blaze-blueprint/src/data.ts, packages/blaze-blueprint/src/schema.ts, packages/blaze-blueprint/src/shared.ts, packages/blaze-tsconfig/base.json, packages/blaze-tx/src/data.ts
This adds strong typing for the blueprint generation code, and improves the format of the generated code.
This is in preparation to rewrite the data serialization stuff to better handle recursive types.
=> Add typings for blueprint code

.changeset/twenty-scissors-sparkle.md, packages/blaze-emulator/src/emulator.ts, packages/blaze-emulator/src/provider.ts, packages/blaze-query/src/blockfrost.ts, packages/blaze-query/src/hydra.ts, packages/blaze-query/src/kupmios.ts, packages/blaze-query/src/maestro.ts, packages/blaze-query/src/provider.ts
I'm not super happy with this solution, but it should unblock some other work I'm doing; Open to feedback in the mean time on how to make this better!
=> Slot <> Unix time conversion functions

.changeset/curvy-dots-check.md, packages/blaze-query/src/blockfrost.ts
This was getting really really slow because we were fetching a ton of unneccesary script refs from blockfrost
=> More intelligent script ref fetching in blockfrost

packages/blaze-emulator/src/emulator.ts, packages/blaze-emulator/test/Emulator.test.ts, packages/blaze-emulator/test/__snapshots__/Emulator.test.ts.snap
No changeset required for this, just adding additional coverage.
=> chore: adds test coverage for inbalanced transactions in the emulator

.changeset/lemon-balloons-melt.md, packages/blaze-data/src/index.ts
Implements a fix mentioned in https://github.com/sinclairzx81/typebox/issues/205
=> Export typebox types from /data

.changeset/tough-houses-fix.md, packages/blaze-emulator/package.json, packages/blaze-emulator/src/emulator.ts, packages/blaze-emulator/src/provider.ts, packages/blaze-emulator/test/Emulator.test.ts, packages/blaze-emulator/test/Provider.test.ts
=> Add test coverage to emulator pkg

packages/blaze-blueprint/package.json, packages/blaze-core/package.json, packages/blaze-core/src/nativescript.ts, packages/blaze-data/package.json, packages/blaze-emulator/package.json, packages/blaze-ogmios/package.json, packages/blaze-query/package.json, packages/blaze-sdk/package.json, packages/blaze-tx/package.json, packages/blaze-uplc/package.json, packages/blaze-vm/package.json, packages/blaze-wallet/package.json, pnpm-lock.yaml
just trying this out, we don't actually need to do it
=> upgrade to tsdown
